version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test


  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test